-- Active: 1777829314445@@127.0.0.1@3307@cos
CREATE DATABASE IF NOT EXISTS COS;
USE COS;

SET AUTOCOMMIT = 0;
SELECT @@autocommit;

CREATE TABLE LAB_RESULT (
    LabResultID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    OrderID INT NOT NULL,
    AuthorizedByID INT NOT NULL,
    TestName VARCHAR(150)    NOT NULL,
    Findings TEXT,
    ResultValue VARCHAR(100),
    ImageURL VARCHAR(255),
    ResultDate DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (OrderID) REFERENCES MEDICAL_ORDER(OrderID)
        ON UPDATE CASCADE ON DELETE RESTRICT,
    FOREIGN KEY (AuthorizedByID) REFERENCES MEDICAL_STAFF(StaffID)
        ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE TABLE MEDICAL_RECORD (
    RecordID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    VisitID INT NOT NULL,
    AuthorID INT NOT NULL,
    RecordType VARCHAR(100) NOT NULL,
    Content TEXT,
    Version INT NOT NULL DEFAULT 1,
    UpdatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
		ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (VisitID)   REFERENCES VISIT(VisitID)
        ON UPDATE CASCADE ON DELETE RESTRICT,
    FOREIGN KEY (AuthorID)  REFERENCES MEDICAL_STAFF(StaffID)
        ON UPDATE CASCADE ON DELETE RESTRICT
);



CREATE TABLE MEDICAL_ORDER (
    OrderID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    VisitID INT NOT NULL,
    IssuedByID INT NOT NULL,
    OrderType VARCHAR(100)    NOT NULL,
    Instructions TEXT,
    Priority ENUM('Routine', 'Urgent', 'STAT') NOT NULL DEFAULT 'Routine',
    Status ENUM('Pending', 'In Progress', 'Completed', 'Cancelled') NOT NULL DEFAULT 'Pending',
    CreatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (VisitID) REFERENCES VISIT(VisitID)
        ON UPDATE CASCADE ON DELETE RESTRICT,
    FOREIGN KEY (IssuedByID) REFERENCES MEDICAL_STAFF(StaffID)
        ON UPDATE CASCADE ON DELETE RESTRICT
);


CREATE TABLE MEDICAL_STAFF (
    StaffID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    InstitutionID INT NOT NULL,
    Name VARCHAR(100) NOT NULL,
    Role ENUM('Doctor', 'Nurse', 'Admin') NOT NULL,
    Specialization VARCHAR(100),
    Phone VARCHAR(20),
    FOREIGN KEY (InstitutionID) REFERENCES CLINICAL_INSTITUTION(InstitutionID)
        ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE TABLE PATIENT (
    PatientID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    FullName VARCHAR(100) NOT NULL,
    IC_Passport VARCHAR(20) NOT NULL UNIQUE,
    DOB DATE NOT NULL,
    Gender ENUM('Male', 'Female', 'Other') NOT NULL,
    BloodType ENUM('A+','A-','B+','B-','AB+','AB-','O+','O-') NOT NULL,
    AllergyHistory TEXT
);

CREATE TABLE PRESCRIPTION (
    PrescriptionID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    VisitID INT NOT NULL,
    DoctorID INT NOT NULL,
    MedicineName VARCHAR(150)    NOT NULL,
    Dosage VARCHAR(100) NOT NULL,
    Frequency VARCHAR(100) NOT NULL,
    DurationDays INT NOT NULL,
    FOREIGN KEY (VisitID) REFERENCES VISIT(VisitID)
        ON UPDATE CASCADE ON DELETE RESTRICT,
    FOREIGN KEY (DoctorID) REFERENCES MEDICAL_STAFF(StaffID)
        ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE TABLE REFERRAL (
    ReferralID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    VisitID INT NOT NULL,
    FromStaffID INT NOT NULL,
    ToInstitutionID INT NOT NULL,
    TargetSpecialty VARCHAR(100),
    ClinicalReason TEXT,
    Status ENUM('Pending', 'Accepted', 'Completed', 'Rejected') NOT NULL DEFAULT 'Pending',
    FOREIGN KEY (VisitID) REFERENCES VISIT(VisitID)
        ON UPDATE CASCADE ON DELETE RESTRICT,
    FOREIGN KEY (FromStaffID) REFERENCES MEDICAL_STAFF(StaffID)
        ON UPDATE CASCADE ON DELETE RESTRICT,
    FOREIGN KEY (ToInstitutionID) REFERENCES CLINICAL_INSTITUTION(InstitutionID)
        ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE TABLE VISIT (
    VisitID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    PatientID INT NOT NULL,
    AppointmentID INT,
    PrimaryDoctorID INT NOT NULL,
    VisitDate DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    VisitType VARCHAR(100) NOT NULL,
    Status ENUM('In Progress', 'Completed', 'Cancelled') NOT NULL DEFAULT 'In Progress',
    FOREIGN KEY (PatientID) REFERENCES PATIENT(PatientID)
        ON UPDATE CASCADE ON DELETE RESTRICT,
    FOREIGN KEY (AppointmentID) REFERENCES APPOINTMENT(AppointmentID)
        ON UPDATE CASCADE ON DELETE SET NULL,
    FOREIGN KEY (PrimaryDoctorID) REFERENCES MEDICAL_STAFF(StaffID)
        ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE TABLE VITAL_SIGNS (
    VitalID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    VisitID INT NOT NULL,
    OrderID INT NOT NULL,
    RecordedByID INT NOT NULL,
    BodyTemp DECIMAL(4,1) NOT NULL,
    HeartRate INT NOT NULL,
    BloodPressure VARCHAR(10) NOT NULL,
    OxygenSaturation DECIMAL(5,2) NOT NULL,
    RecordedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (VisitID) REFERENCES VISIT(VisitID)
        ON UPDATE CASCADE ON DELETE RESTRICT,
    FOREIGN KEY (OrderID) REFERENCES MEDICAL_ORDER(OrderID)
        ON UPDATE CASCADE ON DELETE RESTRICT,
    FOREIGN KEY (RecordedByID)  REFERENCES MEDICAL_STAFF(StaffID)
        ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE TABLE APPOINTMENT (
    AppointmentID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    PatientID INT NOT NULL,
    StaffID INT NOT NULL,
    ScheduledTime DATETIME NOT NULL,
    Reason VARCHAR(255),
    Status ENUM('Scheduled', 'Completed', 'Cancelled', 'No-Show') NOT NULL DEFAULT 'Scheduled',
    FOREIGN KEY (PatientID) REFERENCES PATIENT(PatientID)
        ON UPDATE CASCADE ON DELETE RESTRICT,
    FOREIGN KEY (StaffID)   REFERENCES MEDICAL_STAFF(StaffID)
        ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE TABLE CLINICAL_INSTITUTION (
    InstitutionID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(150) NOT NULL,
    Type VARCHAR(100) NOT NULL,
    Address VARCHAR(255) NOT NULL
);

CREATE TABLE EMERGENCY_CONTACT (
    ContactID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    PatientID INT NOT NULL,
    Name VARCHAR(100) NOT NULL,
    Relationship VARCHAR(50) NOT NULL,
    Phone VARCHAR(20) NOT NULL,
    FOREIGN KEY (PatientID) REFERENCES PATIENT(PatientID)
        ON UPDATE CASCADE ON DELETE CASCADE
);